version: "3.8"

services:

  db:
    image: mysql:8.0
    container_name: movie_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DB}
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./updated_movies.sql:/docker-entrypoint-initdb.d/init.sql  # seeds your DB on first run
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build: ./backend
    container_name: movie_backend
    restart: always
    ports:
      - "5001:5001"
    environment:
      - MYSQL_HOST=db
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DB=${MYSQL_DB}
      - MYSQL_PORT=3306
      - FLASK_ENV=production
    depends_on:
      db:
        condition: service_healthy

  frontend:
    build:
      context: ./frontend
      args:
        - VITE_USE_MOCK=false
        - VITE_API_URL=/api
    container_name: movie_frontend
    restart: always
    ports:
      - "5173:80"
    depends_on:
      - backend

volumes:
  db_data: